### PR TITLE
fix: fallback to manifest values if they're not specified in ExtismPluginOptions

### LINKED ISSUE #55: manifest: support `memory.max_http_response_bytes` field
See https://github.com/extism/extism/pull/674

### LINKED ISSUE #58: `Manifest.config` is not being used
See: https://github.com/extism/js-sdk/blob/6e4903eba8bfcb58ca450b969c865e1cc435b08f/src/interfaces.ts#L277

Instead, `ExtismPluginOptions.config` is being used: https://github.com/extism/js-sdk/blob/6e4903eba8bfcb58ca450b969c865e1cc435b08f/src/interfaces.ts#L129

### PR DESCRIPTION
**Pull request by mhmd-azeez**
Fixes #58 
Fixes #55 

- [x] config
- [x] allowed_hosts
- [x] allowed_paths
- [x] memory
- [ ] timeout
- [x] tests

### CODE REVIEW

**Comment by mhmd-azeez** [comment]
@chrisdickinson i am on the fence about whether we should contact the fields, or only use manifest when nothing is specified in ExtismPluginOptions

File: src/mod.ts [hunk 1]
```diff
@@ -91,7 +99,7 @@ export async function createPlugin(
     );
   }
 
-  const [names, moduleData] = await _toWasmModuleData(await Promise.resolve(manifest), opts.fetch ?? fetch);
+  const [names, moduleData] = await _toWasmModuleData(m, opts.fetch ?? fetch);
```
Comment (chrisdickinson) [inline src/mod.ts:102]: In order to support manifest options when the manifest is provided via `fetch`, we might rework `_toWasmModuleData` to return a third item, `manifestOpts`, then perform this call before normalizing the options in this function.

[`intoManifest`](https://github.com/extism/js-sdk/blob/main/src/manifest.ts#L79) is the chokepoint at which all the disparate input types are unified into something "manifest-like", so we could extract manifest-provided options [here](https://github.com/extism/js-sdk/blob/main/src/manifest.ts#L160) and then use them in `createPlugin` to finish normalizing the input options.

**Review by chrisdickinson — COMMENTED** [review]
Thanks for taking a look at this! This PR jogs my memory - I think I was _also_ on the fence about whether to allow the manifest to control `allowedHosts`/`allowedPaths` in the absence of explicit configuration from the caller. Since the manifest can be loaded via URL it strikes me that the manifest author and the sdk integrator might not be the same party.

At the risk of complicating things, I'd almost want to have an explicit `createPlugin`-only option like `allowManifestConfig` to determine what options the manifest is allowed to control.

**Comment by mhmd-azeez** [comment]
> At the risk of complicating things, I'd almost want to have an explicit createPlugin-only option like allowManifestConfig to determine what options the manifest is allowed to control.

I am hesitant about this because this behavior is different from what the other SDKs are doing. Curious what @bhelx thinks

File: src/mod.ts (hunk 1 above)
Comment (mhmd-azeez) [reply src/mod.ts]: is this what you meant?

https://github.com/extism/js-sdk/blob/d3e0dbcb9575f8c93307bca0f03a6e31cf3ab132/src/manifest.ts#L97

Comment (chrisdickinson) [reply src/mod.ts]: Yep! That's perfect, thank you!

**Comment by mhmd-azeez** [comment]
Seems like manifest is missing a few options, I will try to add them all in this PR

File: src/utils.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
+export function withTimeout<T>(promise: Promise<T>, timeoutMs?: number | undefined): Promise<T> {
```
Comment (chrisdickinson) [inline src/utils.ts:1]: To double-check semantics of the other sdks - in other sdks, it looks like if we cancel an operation due to a timeout, we expect the operation to halt (using [`increment_epoch`](https://docs.rs/wasmtime/latest/wasmtime/struct.Engine.html#method.increment_epoch)).

If I understand this correctly, this is kind of a tricky feature to implement in JS. We can support this for `runInWorker: true` plugins – we can kill the worker thread on timeout – but I don't think we have a cancelable promise otherwise. This would be user-visible if the plugin has access to host functions.

Comment (mhmd-azeez) [reply src/utils.ts]: Great points, while I was able to implement it in the background plugin, the foreground plugin doesn't seem to work:
https://github.com/extism/js-sdk/pull/73/commits/43e75aceff971c145b353c26a278e877780c0d39

If I can't find a solution, I might ignore timeout for now and create a separate issue for it

**Comment by mhmd-azeez** [comment]
@chrisdickinson i have added checks for cancellation before all of the extism functions + host functions. So the function call not being cancelled shouldn't be user visible. The only issue is timeouts don't seem to work while a wasm function is being executed. So ForegroundPlugin can't set cancelled to true. Any ideas?

**Comment by chrisdickinson** [comment]
> @chrisdickinson i have added checks for cancellation before all of the extism functions + host functions. So the function call not being cancelled shouldn't be user visible. The only issue is timeouts don't seem to work while a wasm function is being executed. So ForegroundPlugin can't set cancelled to true. Any ideas?

Ah yeah – unfortunately, since JS is single-threaded & Wasm runs on the main thread, control is never yielded back to the event loop to trigger the timer. I think it's probably best to make timers a `runInWorker`-only feature. If we do that, I think we might be able to remove the cancellation checks on `CallContext` and replace them with a `worker.terminate()` call (& some code to "restart" the worker from `src/background-worker.ts`.)

**Comment by mhmd-azeez** [comment]
@chrisdickinson thanks for your suggestion, I think it's much more robust now. Please take a look and lt me know if you have any more feedback

**Comment by mhmd-azeez** [comment]
for some reason, the tests fail in bun

**Comment by mhmd-azeez** [comment]
okay, not sure why only Bun is getting stuck. This is the minimal repro:
https://github.com/extism/js-sdk/pull/73/commits/b6300e4ef7b2e4d10327902b1e7d8dc4f65f32ef

@chrisdickinson any ideas?

**Comment by bhelx** [comment]
> Thanks for taking a look at this! This PR jogs my memory - I think I was also on the fence about whether to allow the manifest to control allowedHosts/allowedPaths in the absence of explicit configuration from the caller. Since the manifest can be loaded via URL it strikes me that the manifest author and the sdk integrator might not be the same party.
> At the risk of complicating things, I'd almost want to have an explicit createPlugin-only option like allowManifestConfig to determine what options the manifest is allowed to control.

@chrisdickinson I think it's okay that manifest can be a url, but we should just draw bright lines around it. manifest wasn't ever really meant to be something a plug-in dev could author. We have had discussions about having some kind of separate "manifest override" kind of object that would give the host the controls to allow a guest to override specific parts of the manifest. But I think that is a bigger extism wide thing we need to propose and discuss.

**Comment by chrisdickinson** [comment]
> any ideas?

Nothing too concrete. When I've run into Bun hangs and crashes before, it's been an outcome of their focus on performance. That tends to lead to bugs like subtle timing changes – so my first guess would be that they're doing something with the worker that causes it to spin up _very_ quickly the second time its spawned, possibly before we've attached a message listener in the host. We could test this hypothesis by adding some logs to the host to see if or where the `createWorker` call is hanging – then, if it's hanging while waiting on [either of these](https://github.com/extism/js-sdk/blob/b6300e4ef7b2e4d10327902b1e7d8dc4f65f32ef/src/background-plugin.ts#L514-L534) functions, we might add a `setTimeout` delay of 1ms or so to the worker before sending the initialized message.

The other thing that strikes me is that we null out `this.#request` [here](https://github.com/extism/js-sdk/blob/b6300e4ef7b2e4d10327902b1e7d8dc4f65f32ef/src/background-plugin.ts#L67). That might be enough for the promise to get GC'd in other runtimes, but it could be that Bun's hanging on to it. It might be best to `reject` that promise by calling `if (this.#request) this.#request[1](new Error('timed out'))`.

**Comment by mhmd-azeez** [comment]
Ah, it's actually node getting stuck at the end

**Comment by mhmd-azeez** [comment]
Sorry for doubting you Bun

**Comment by bhelx** [comment]
> Sorry for doubting you Bun

check your nodejs bias at the door!

**Comment by mhmd-azeez** [comment]
Okay, as far as I can see, NodeJS can't terminate a worker that's executing a rogue wasm function. Here is a repro in our case:

```ts
  async call(funcName: string, input?: string | Uint8Array): Promise<PluginOutput | null> {
    const index = this.#context[STORE](input);

    try {
      const [errorIdx, outputIdx] = CAPABILITIES.supportsTimeouts ?
        await withTimeout(this.callBlock(funcName, index), this.opts.timeoutMs) :
        await this.callBlock(funcName, index);

      const shouldThrow = errorIdx !== null;
      const idx = errorIdx ?? outputIdx;

      if (idx === null) {
        return null;
      }

      const block = this.#context[GET_BLOCK](idx);

      if (block === null) {
        return null;
      }

      const buf = new PluginOutput(
        CAPABILITIES.allowSharedBufferCodec ? block.buffer : new Uint8Array(block.buffer).slice().buffer,
      );

      if (shouldThrow) {
        const msg = new TextDecoder().decode(buf);
        throw new Error(`Plugin-originated error: ${msg}`);
      }

      return buf;
    } catch (err) {
      if (err instanceof Error && err.message === 'Function call timed out') {
        console.log('Function call timed out, restarting worker')
        await this.restartWorker();
      }

      throw err;
    }
  }
```

```ts
test('plugin functions cant exceed specified timeout', async () => {
    let x = 0;

    try {
      const plugin = await createPlugin(
        { wasm: [{ url: 'http://localhost:8124/wasm/sleep.wasm' }], timeoutMs: 1 },
        {
          useWasi: true,
          functions: {
            "extism:host/user": {
              notify() {
                x++;
              },
              get_now_ms() {
                return BigInt(Date.now());
              }
            }
          },
          runInWorker: true
        });

      try {
        const [err, _] = await plugin.call('sleep', JSON.stringify({ duration_ms: 100 })).then(
          (data) => [null, data],
          (err) => [err, null],
        );

        assert(err)
        assert.equal(err.message, 'Function call timed out');
        await new Promise(resolve => setTimeout(resolve, 200));
        assert.equal(x, 0)

      } finally {
        await plugin.close();
      }
    }
    catch (err) {
      if (!CAPABILITIES.supportsTimeouts) {
        assert(err instanceof Error);
        assert.equal(err.message, 'Cannot set timeoutMs; current context does not support timeouts');
      }

      throw err;
    }
  });

async restartWorker() {
    await this.close();

    this.#context[RESET]();
    this.#request = null;

    this.worker = await createWorker(this.opts, this.names, this.modules, this.sharedData);
    this.worker.on('message', (ev) => this.#handleMessage(ev));
  }

async close(): Promise<void> {
    if (this.worker) {
      this.worker.terminate();
      this.worker = null as any;
    }
  }
```

Everything is executed (even the terminate call), but the process never exits.

I am going to skip timeout in this PR and create a separate issue for it

**Comment by mhmd-azeez** [comment]
This PR is ready for review

File: src/background-plugin.ts [hunk 3]
```diff
@@ -453,7 +469,12 @@ class HttpContext {
     });
 
     this.lastStatusCode = response.status;
-    const result = callContext.store(new Uint8Array(await response.arrayBuffer()));
+
+    let bytes = this.memoryOptions.maxHttpResponseBytes ?
+      await readBodyUpTo(response, this.memoryOptions.maxHttpResponseBytes) :
```
Comment (chrisdickinson) [inline src/background-plugin.ts:474]: We may want to `catch` here, store the error, and return a `0` value.

**Review by chrisdickinson — APPROVED** [review]
Whew, great work! I left some comments about places where we might still diverge from other extism host sdk behavior with regards to thrown errors. I also left an optional comment about a foible of mine.

If you'd like to merge from here I think this PR brings us a lot closer to the behavior of other sdks – we can make a ticket for handling error states more akin to how the rust-sdk handles it.

File: src/background-plugin.ts [hunk 4]
```diff
@@ -126,6 +136,10 @@ class BackgroundPlugin {
 
     this.#request = [resolve as any, reject as any];
 
+    if (!this.worker) {
+      throw new Error('worker has crashed');
+    }
```
[the remark this answers is not in the document]
Comment (mhmd-azeez) [reply src/background-plugin.ts]: yeah, i agree. i have changed the constructor to pass in an initial worker

**Review by chrisdickinson — APPROVED** [review]
LGTM! Great work!
